import { RawMaterial } from '../../domain/entities/raw-material.entity';
import { Product } from '../../domain/entities/product.entity';
import { Recipe } from '../../domain/entities/recipe.entity';
import { Calculation } from '../../domain/entities/calculation.entity';
import { MarginSimulation } from '../../domain/entities/margin-simulation.entity';
import { ProfitAnalysis } from '../../domain/entities/profit-analysis.entity';

const now = new Date().toISOString();

export const seedRawMaterials: RawMaterial[] = [
  {
    id: 'rm-001',
    name: 'Tepung Terigu',
    unit: 'kg',
    pricePerUnit: 15000,
    stockQuantity: 25,
    category: 'Bahan Pokok',
    notes: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'rm-002',
    name: 'Gula Pasir',
    unit: 'kg',
    pricePerUnit: 18000,
    stockQuantity: 15,
    category: 'Bahan Pokok',
    notes: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'rm-003',
    name: 'Telur',
    unit: 'kg',
    pricePerUnit: 30000,
    stockQuantity: 10,
    category: 'Bahan Pokok',
    notes: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'rm-004',
    name: 'Mentega',
    unit: 'kg',
    pricePerUnit: 45000,
    stockQuantity: 5,
    category: 'Bahan Pokok',
    notes: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'rm-005',
    name: 'Keju Parut',
    unit: 'kg',
    pricePerUnit: 120000,
    stockQuantity: 3,
    category: 'Bahan Tambahan',
    notes: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'rm-006',
    name: 'Selai Nanas',
    unit: 'kg',
    pricePerUnit: 85000,
    stockQuantity: 4,
    category: 'Bahan Tambahan',
    notes: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'rm-007',
    name: 'Susu Bubuk',
    unit: 'kg',
    pricePerUnit: 55000,
    stockQuantity: 6,
    category: 'Bahan Pokok',
    notes: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'rm-008',
    name: 'Kemasan Toples',
    unit: 'pcs',
    pricePerUnit: 8500,
    stockQuantity: 100,
    category: 'Kemasan',
    notes: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'rm-009',
    name: 'Vanili Bubuk',
    unit: 'gram',
    pricePerUnit: 200,
    stockQuantity: 500,
    category: 'Bumbu',
    notes: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'rm-010',
    name: 'Garam',
    unit: 'gram',
    pricePerUnit: 10,
    stockQuantity: 1000,
    category: 'Bumbu',
    notes: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const seedProducts: Product[] = [
  {
    id: 'prd-001',
    name: 'Kue Nastar',
    description: 'Kue nastar klasik dengan selai nanas homemade',
    category: 'Kue',
    sellingPrice: 75000,
    imageUri: null,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prd-002',
    name: 'Kastengel',
    description: 'Kue keju khas Belanda, renyah dan gurih',
    category: 'Kue',
    sellingPrice: 85000,
    imageUri: null,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prd-003',
    name: 'Lidah Kucing',
    description: 'Kue kering lidah kucing renyah',
    category: 'Kue',
    sellingPrice: 65000,
    imageUri: null,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const seedRecipes: Recipe[] = [
  {
    id: 'rcp-001',
    productId: 'prd-001',
    rawMaterialId: 'rm-001',
    quantity: 0.5,
    unit: 'kg',
    createdAt: now,
  },
  {
    id: 'rcp-002',
    productId: 'prd-001',
    rawMaterialId: 'rm-002',
    quantity: 0.2,
    unit: 'kg',
    createdAt: now,
  },
  {
    id: 'rcp-003',
    productId: 'prd-001',
    rawMaterialId: 'rm-003',
    quantity: 0.3,
    unit: 'kg',
    createdAt: now,
  },
  {
    id: 'rcp-004',
    productId: 'prd-001',
    rawMaterialId: 'rm-004',
    quantity: 0.25,
    unit: 'kg',
    createdAt: now,
  },
  {
    id: 'rcp-005',
    productId: 'prd-001',
    rawMaterialId: 'rm-006',
    quantity: 0.3,
    unit: 'kg',
    createdAt: now,
  },
  {
    id: 'rcp-006',
    productId: 'prd-001',
    rawMaterialId: 'rm-008',
    quantity: 1,
    unit: 'pcs',
    createdAt: now,
  },
  {
    id: 'rcp-007',
    productId: 'prd-002',
    rawMaterialId: 'rm-001',
    quantity: 0.4,
    unit: 'kg',
    createdAt: now,
  },
  {
    id: 'rcp-008',
    productId: 'prd-002',
    rawMaterialId: 'rm-004',
    quantity: 0.3,
    unit: 'kg',
    createdAt: now,
  },
  {
    id: 'rcp-009',
    productId: 'prd-002',
    rawMaterialId: 'rm-005',
    quantity: 0.2,
    unit: 'kg',
    createdAt: now,
  },
  {
    id: 'rcp-010',
    productId: 'prd-002',
    rawMaterialId: 'rm-003',
    quantity: 0.2,
    unit: 'kg',
    createdAt: now,
  },
  {
    id: 'rcp-011',
    productId: 'prd-002',
    rawMaterialId: 'rm-008',
    quantity: 1,
    unit: 'pcs',
    createdAt: now,
  },
];

export const seedCalculations: Calculation[] = [
  {
    id: 'cal-001',
    productId: 'prd-001',
    totalHpp: 48500,
    totalMaterialCost: 38500,
    overheadCost: 5000,
    laborCost: 3000,
    otherCost: 2000,
    quantityProduced: 1,
    hppPerUnit: 48500,
    notes: 'Produksi batch pertama',
    createdAt: now,
  },
  {
    id: 'cal-002',
    productId: 'prd-002',
    totalHpp: 56500,
    totalMaterialCost: 43500,
    overheadCost: 6000,
    laborCost: 4000,
    otherCost: 3000,
    quantityProduced: 1,
    hppPerUnit: 56500,
    notes: null,
    createdAt: now,
  },
];

export const seedMarginSimulations: MarginSimulation[] = [
  {
    id: 'mar-001',
    calculationId: 'cal-001',
    productId: 'prd-001',
    desiredMarginPercent: 35,
    suggestedPrice: 74615,
    estimatedProfitPerUnit: 26115,
    estimatedTotalProfit: 2611500,
    isActive: true,
    createdAt: now,
  },
  {
    id: 'mar-002',
    calculationId: 'cal-002',
    productId: 'prd-002',
    desiredMarginPercent: 33,
    suggestedPrice: 84328,
    estimatedProfitPerUnit: 27828,
    estimatedTotalProfit: 2782800,
    isActive: true,
    createdAt: now,
  },
];

export const seedProfitAnalyses: ProfitAnalysis[] = [
  {
    id: 'prf-001',
    productId: 'prd-001',
    periodStart: '2026-01-01',
    periodEnd: '2026-03-31',
    totalRevenue: 15000000,
    totalHpp: 9700000,
    grossProfit: 5300000,
    operationalCost: 2000000,
    netProfit: 3300000,
    marginPercent: 35.33,
    notes: 'Kuartal 1 2026',
    createdAt: now,
  },
  {
    id: 'prf-002',
    productId: 'prd-002',
    periodStart: '2026-01-01',
    periodEnd: '2026-03-31',
    totalRevenue: 12750000,
    totalHpp: 8475000,
    grossProfit: 4275000,
    operationalCost: 1500000,
    netProfit: 2775000,
    marginPercent: 33.53,
    notes: null,
    createdAt: now,
  },
];
